### PR TITLE
New name-Card added /Arvind Yadav

### PR DESCRIPTION
**Pull request by Arvind0302**
I had added my name card with all the necessary details.

### CODE REVIEW

**Review by shubhanshu02 — CHANGES_REQUESTED** [review]
Changes mentioned in #84

**Comment by Arvind0302** [comment]
So what should i do now ,should i perform the task drom beigning again .
Or anything else

**Comment by shubhanshu02** [comment]
> So what should i do now ,should i perform the task drom beigning again . Or anything else

See the changes in the [File Changed](https://github.com/COPS-IITBHU/csoc-2021-namecards/pull/87/files) section, remove the corresponding changes in the file and then commit changes.

Or you can revert your changes and just copy-paste your object to the array without altering the existing code.

**Comment by Arvind0302** [comment]
bhaiya, i didn't get your point what to do . Plz tell me again..
Is there any option to remove this commit and i will do this task again

**Pull request closed without merging**
