### PR TITLE
Added card:Sai Sumanth

### PR DESCRIPTION
**Pull request by saisumanthkumar**

### CODE REVIEW

**Comment by subodhk01** [comment]
Hey fellow dev, there has been a slight change in the contributor's json structure, `id` has been changed to `handle_name`.

Please accommodate the following change in your code too.

**Comment by saisumanthkumar** [comment]
Ok

**Comment by saisumanthkumar** [comment]
Modified ID -> handle_name

**Review by shubhanshu02 — CHANGES_REQUESTED** [review]
@saisumanthkumar, as per the task description (ref: [task description](https://www.notion.so/CSOC-21-Dev-014d55c642a74e6e885216e93c6e6f66?p=b6a82dc57d874f05865237640727db29)), the pull request must be made from a separate branch (other than **main**). Please close this PR and complete the task from a separate branch.

**Comment by saisumanthkumar** [comment]
Will create new pull request

**Pull request closed without merging**
